---
- name: Assemble and Push configuration
  hosts: all
  connection: local
  gather_facts: no

  tasks:
  - name: Assemble configuration
    assemble: src={{config_dir}}/{{hostname}}/ dest={{config_dir}}/{{hostname}}/running.conf
    changed_when: False

  - name: Push configuration with napalm
    napalm_install_config:
        hostname={{hostname}}
        username={{user}}
        dev_os={{os}}
        password={{passwd}}
        config_file={{config_dir}}/{{hostname}}/running.conf
        commit_changes=True
        replace_config=False
        diff_file={{config_dir}}/{{hostname}}/diff
